#!/bin/bash
# New devs, run this once to enable this script: chmod +x ./start
# To start the app run: ./start

# Spin up a PHP web server on a project directory

# error_log(print_r('endDT', true));

php -S localhost:8081;